### ISSUE TITLE
Command damageModel cannot be called using eval()

### ISSUE THREAD

**Issue by EmmanouilChaitas** [peer-open-source/xara#33]
When trying to use the eval() command, damageModel options cannot be evaluated. The same commands register normally when interacting with the OpenSees.exe (v.3.7.0).

The installed sees version is 0.1.8 and pip cannot find any newer versions (specifically v.0.1.10).

Example statement:
model.eval("damageModel ParkAng 1 0.05 0.1 100.0")

The following error is raised:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\opensees\tcl.py", line 155, in eval
    return self._tcl.tk.eval(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: invalid command name "damageModel"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\manue\Desktop\test_vecchio_RT.py", line 98, in <module>
    model.eval('damageModel ParkAng 1 0.05 0.1 100.0')
  File "C:\ProgramData\anaconda3\Lib\site-packages\opensees\openseespy.py", line 400, in eval
    return self._openseespy.eval(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\opensees\openseespy.py", line 196, in eval
    return self._interp.eval(cmd)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\opensees\tcl.py", line 158, in eval
    raise TclError(self._tcl.getvar("errorInfo"))
opensees.tcl.TclError: invalid command name "damageModel"
    while executing
"damageModel ParkAng 1 0.05 0.1 100.0"

**Comment by claudioperez** [comment]
Hi Emmanouil,
Sorry for the late response, I'm just seeing this now! The `DamageModel` was temporarily disabled in OpenSeesRT to focus development on the core features and optimizations. However, it shouldn't take very long for me to add it back in. I'll take a look and get back to you with any updates!

**Comment by EmmanouilChaitas** [comment]
Hi Claudio,

I'll keep an eye out for any updated versions!
